Repository oqtopus-team/tranqu, pull requests merged in 2024-12, with the labels that each got.

#9 chore: add PR labeler
  .github/workflows/labeler.yaml
  README.md
  docs/index.md
Labels: chore

#10 fix: add the github_token parameter to labeler
  .github/workflows/labeler.yaml
Labels: bugfix

#12 fix: improve labeler workflow
  .github/workflows/labeler.yaml
Labels: bugfix

#16 chore: add vs code settings
  .editorconfig
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: chore

#13 default transpiler lib
  pyproject.toml
  src/tranqu/tranqu.py
  src/tranqu/transpiler/__init__.py
  src/tranqu/transpiler/transpiler_manager.py
  src/tranqu/transpiler_dispatcher.py
  tests/tranqu/test_tranqu.py
  tests/tranqu/transpiler/test_transpiler_manager.py
Labels: feature, test

#17 feat: add default_transpiler_lib parameter to register_default_transpiler_lib function
  src/tranqu/tranqu.py
  src/tranqu/transpiler/transpiler_manager.py
  tests/tranqu/transpiler/test_transpiler_manager.py
Labels: feature

#18 docs: add explanations of build-in types
  docs/usage/how_it_works.ipynb
Labels: documentation

#19 chore: delete uv.lock" from .gitignore
  .gitignore
Labels: chore

#20 add ouqu-tp support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/actions/setup-staq/action.yml
  .github/workflows/ci.yaml
  docs/usage/how_it_works.ipynb
  pyproject.toml
  src/tranqu/device_converter/__init__.py
  src/tranqu/device_converter/oqtopus_to_ouqu_tp_device_converter.py
  src/tranqu/device_converter/qiskit_to_ouqu_tp_device_converter.py
  src/tranqu/program_converter/__init__.py
  src/tranqu/program_converter/openqasm3_to_ouqu_tp_program_converter.py
  src/tranqu/program_converter/ouqu_tp_to_openqasm3_program_converter.py
  src/tranqu/program_converter/ouqu_tp_to_qiskit_program_converter.py
  src/tranqu/program_converter/qiskit_to_ouqu_tp_program_converter.py
  src/tranqu/tranqu.py
  src/tranqu/transpiler/__init__.py
  src/tranqu/transpiler/base_qiskit_transpiler.py
  src/tranqu/transpiler/ouqu_tp_transpiler.py
  src/tranqu/transpiler/qiskit_layout_mapper.py
  src/tranqu/transpiler/qiskit_stats_extractor.py
  src/tranqu/transpiler/qiskit_transpiler.py
  tests/tranqu/program_converter/test_qiskit_to_ouqu_tp_program_converter.py
  tests/tranqu/transpiler/test_ouqu_tp_transpiler.py
  uv.lock
Labels: feature
